### ISSUE TITLE
输入5个数字报意外的换行符

### ISSUE THREAD

**Issue by skymon4** [luobangkui/daletou-numbers#1]
![image](https://user-images.githubusercontent.com/33510540/58527893-23e36d80-8207-11e9-97d1-625407cc2288.png)

**Comment by luobangkui** [comment]
感谢提醒，应该是最后一个数字多输入了一个空格。

**Comment by skymon4** [comment]
没有 我这边没有多输空格 直接回车的

**Comment by luobangkui** [comment]
感谢，已经fixed
